// <auto-generated />
namespace Nance.EFRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BaseItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201502152355580_BaseItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
