// <auto-generated />
namespace Nance.EFRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class testmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201502160707523_testmig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
